name: Pip

on:
  push:
    branches:    
      - 'main'
      - 'feature/**'
  pull_request:
    types: [opened, reopened,edited]

jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
        upgrade: true
    - run: python spcli/sp.py -v # <-- only one value is allowed